test new image: cimg-build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,9 +1,14 @@
 version: 2.1
 
 orbs:
-  cimg: circleci/cimg@0.3.3
+  cimg: circleci/cimg@dev:d365891f2c6242fdc77cd40f9bf4589dcaa3d162
+  aws-cli: circleci/aws-cli@4.1.0
   slack: circleci/slack@4.12.1
   gh: circleci/github-cli@2.2.0
+
+aws-image-tag:
+  # aws-image: &aws-image cimg/aws:2023.07.1
+  aws-image: &aws-image ferriswh33l/sign:2023.10
 
 parameters:
   cron:
@@ -21,36 +26,62 @@ workflows:
     when:
       not: << pipeline.parameters.cron >>
     jobs:
-      - cimg/build-and-deploy:
-          name: "Staging"
+      - cimg-build:
           docker-namespace: ccitest
           docker-repository: node
-          publish-branch: test
           filters:
             branches:
               ignore:
                 - main
-          post-steps:
-            - slack/notify:
-                branch_pattern: release-v.+
-                event: pass
-                mentions: "@jalexchen"
-                template: basic_success_1
           context: cimg-publishing
-      - cimg/build-and-deploy:
-          name: "Deploy"
-          docker-repository: node
-          filters:
-            branches:
-              only:
-                - main
-          post-steps:
-            - slack/notify:
-                branch_pattern: main
-                event: fail
-                mentions: "@images"
-                template: basic_fail_1
-          context: cimg-publishing
+      # - cimg-staging:
+      #     docker-namespace: ccitest
+      #     docker-repository: node
+      #     target-namespace: ccitest
+      #     target-repository: cimg-orb
+      #     organization: circleci-images
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - main
+      #     requires:
+      #       - cimg-build
+      #     context: cimg-publishing
+      # - cimg-verify:
+      #     docker-namespace: ccitest
+      #     docker-repository: node
+      #     target-namespace: ccitest
+      #     target-repository: cimg-orb
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - main
+      #     requires:
+      #       - cimg-staging
+      #     post-steps:
+      #       - slack/notify:
+      #           branch_pattern: release-v.+
+      #           event: pass
+      #           mentions: "@jalexchen"
+      #           template: basic_success_1
+      #     context: cimg-publishing
+      # - cimg-deploy:
+      #     docker-namespace: ccitest
+      #     docker-repository: node
+      #     target-namespace: cimg
+      #     target-repository: node
+      #     organization: circleci-images
+      #     filters:
+      #       branches:
+      #         only:
+      #           - main
+      #     post-steps:
+      #       - slack/notify:
+      #           branch_pattern: main
+      #           event: fail
+      #           mentions: "@images"
+      #           template: basic_fail_1
+      #     context: cimg-publishing
 
 jobs:
   check-feed:
@@ -95,3 +126,146 @@ jobs:
             sudo chmod +x nodeFeed.sh
             git submodule update --init --recursive
             ./nodeFeed.sh
+
+  cimg-build:
+    docker:
+      - image: *aws-image
+    parameters:
+      docker-namespace:
+        type: string
+      docker-repository:
+        type: string
+    steps:
+      - checkout
+      - setup_remote_docker
+      - cimg/build-images:
+          docker-namespace: <<parameters.docker-namespace>>
+          docker-repository: <<parameters.docker-repository>>
+      - run:
+          name: capture metadata
+          command: |
+            cimg capture "<<parameters.docker-namespace>>" "<<parameters.docker-repository>>"
+
+            echo "{}" > "/tmp/registry/metadata.json"
+            for file in /tmp/registry/*-manifest.json; do
+              tag=$(basename ${file%-*})
+              jq --arg tag "$tag" --slurpfile input "$file" '. += { ($tag): $input }' "/tmp/registry/metadata.json" > tmp.json && mv tmp.json "/tmp/registry/metadata.json"
+            done
+      - aws-cli/setup:
+          region: ${AWS_DEFAULT_REGION}
+          role_arn: arn:aws:iam::483285841698:role/cpe-images-bucket-write
+          role_session_name: "write-to-s3"
+      - run:
+          name: Copy to s3
+          command: |
+            cimg copy "<<parameters.docker-namespace>>" "<<parameters.docker-repository>>" "$S3_BUCKET_NAME" "$s3Directory"
+
+  # cimg-staging:
+  #   docker:
+  #     - image: *aws-image
+  #   parameters:
+  #     docker-namespace:
+  #       type: string
+  #     docker-repository:
+  #       type: string
+  #     target-namespace:
+  #       type: string
+  #     target-repository:
+  #       type: string
+  #     organization:
+  #       type: string
+  #   steps:
+  #     - attach_workspace:
+  #         at: /tmp/registry
+  #     - aws-cli/setup:
+  #         region: ${AWS_DEFAULT_REGION}
+  #         role_arn: arn:aws:iam::483285841698:role/cpe-kms-sign
+  #         role_session_name: "sign-docker-images"
+  #     - cimg/sign-images:
+  #         docker-namespace: <<parameters.docker-namespace>>
+  #         docker-repository: <<parameters.docker-repository>>
+  #         organization: <<parameters.organization>>
+  #     - cimg/copy-images:
+  #         docker-namespace: <<parameters.docker-namespace>>
+  #         docker-repository: <<parameters.docker-repository>>
+  #         target-namespace: <<parameters.target-namespace>>
+  #         target-repository: <<parameters.target-namespace>>
+
+  # cimg-verify:
+  #   docker:
+  #     - image: *aws-image
+  #   parameters:
+  #     docker-namespace:
+  #       type: string
+  #     docker-repository:
+  #       type: string
+  #     target-namespace:
+  #       type: string
+  #     target-repository:
+  #       type: string
+  #   steps:
+  #     - checkout
+  #     - aws-cli/setup:
+  #         region: ${AWS_DEFAULT_REGION}
+  #         role_arn: arn:aws:iam::483285841698:role/cpe-images-bucket-read
+  #         role_session_name: "read-from-s3"
+  #     - when:
+  #         condition:
+  #           not: <<pipeline.parameters.check_all>>
+  #         steps:
+  #           - attach_workspace:
+  #               at: /tmp/registry
+  #           - cimg/verify-signature:
+  #               docker-namespace: <<parameters.docker-namespace>>
+  #               docker-repository: <<parameters.docker-repository>>
+  #               target-namespace: <<parameters.target-namespace>>
+  #               target-repository: <<parameters.target-namespace>>
+  #     - when:
+  #         condition: <<pipeline.parameters.check_all>>
+  #         steps:
+  #           - cimg/capture-metadata:
+  #               docker-namespace: <<parameters.docker-namespace>>
+  #               docker-repository: <<parameters.docker-repository>>
+  #           - cimg/verify-all-signatures:
+  #               docker-namespace: <<parameters.docker-namespace>>
+  #               docker-repository: <<parameters.docker-repository>>
+
+  # cimg-deploy:
+  #   docker:
+  #     - image: *aws-image
+  #   parameters:
+  #     docker-namespace:
+  #       type: string
+  #     docker-repository:
+  #       type: string
+  #     target-namespace:
+  #       type: string
+  #     target-repository:
+  #       type: string
+  #     organization:
+  #       type: string
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Check if release commit
+  #         command: |
+  #           if ! git log -1 --pretty=%s | grep "\[release]\"; then
+  #             echo "Not a release commit. Skipping publishing"
+  #             circleci step halt
+  #           fi
+  #     - cimg/capture-metadata:
+  #         docker-namespace: <<parameters.docker-namespace>>
+  #         docker-repository: <<parameters.docker-repository>>
+  #     - aws-cli/setup:
+  #         region: ${AWS_DEFAULT_REGION}
+  #         role_arn: arn:aws:iam::483285841698:role/cpe-kms-sign
+  #         role_session_name: "sign-docker-images"
+  #     - cimg/copy-images:
+  #         docker-namespace: <<parameters.docker-namespace>>
+  #         docker-repository: <<parameters.docker-repository>>
+  #         target-namespace: <<parameters.target-namespace>>
+  #         target-repository: <<parameters.target-namespace>>
+  #     - cimg/sign-images:
+  #         docker-namespace: <<parameters.docker-namespace>>
+  #         docker-repository: <<parameters.docker-repository>>
+  #         organization: <<parameters.organization>>
